### ISSUE TITLE
KCC cover close button in other application ubuntu 

### ISSUE THREAD

**Issue by bkt92** [ciromattia/kcc#118]
![screenshot from 2014-11-23 12 37 57](https://cloud.githubusercontent.com/assets/3808392/5156718/fc681876-730d-11e4-8366-b7b4208992f3.png)

**Comment by Cediddi** [comment]
Can you share your knowledge about the issue. I have other Qt applications on my ubuntu, none of them have such an issue.

**Comment by AcidWeb** [comment]
If you know how to fix it for PyQT 5.4.2 I'm all ears.

**Comment by Cediddi** [comment]
While I was searcing the net, I found this, which probably only work for Linux based systems, but as far as I see, this bug is also only for Linux, especially X11 environments.

https://github.com/kovidgoyal/calibre/tree/master/src/calibre/gui2/dbus_export
DBus interface for System Tray Icons.

Reference:https://bugreports.qt.io/browse/QTBUG-31762

Maybe, for a short time (or long) tray icon may be switched to DBus interface.

**Comment by Cediddi** [comment]
Also a nice commit from Kovid Goyal
Fix system tray icons not working in Ubuntu - https://github.com/kovidgoyal/calibre/commit/7b5bc38d8baa5a9e2ed2f9d5167a2aa0c462a80b

**Comment by AcidWeb** [comment]
I just checked Ubuntu 14.04.2 and 15.
Tray icon work correctly on both.

**Comment by Cediddi** [comment]
I didn't saw your comment, great news. But, how do we install Qt5.4 in 14.04 except compiling from source?

**Comment by AcidWeb** [comment]
No idea.
