### ISSUE TITLE
Display work progress

### ISSUE THREAD

**Issue by ciromattia** [ciromattia/kcc#13]
Improve GUI displaying what file we're processing and giving an explicit progress status.

**Comment by FreeER** [comment]
I don't suppose this could be reopened lol
Decided to put an entire series into one file so I wouldn't be constantly switching files/books on the kindle which is a bit of a slow process, it came out to ~500 MB. Then I found out kindle pw doesn't support cbz so I'm going to have to convert it and KCC came up in searching.

So obviously it's going to take awhile... but I have no clue whatsoever as to how long. All I know is that the program hasn't frozen/crashed because it's got a couple moving bits... no guess-timated ETA, no %, no x/n images or x/n chapters/folders etc.

I expect to do the same with a few others as well since I'm fairly new to comics and I'm sure there's a lot of in-progress/complete ones I'd like to be able to read conveniently...

Anyways, thanks for taking the time to read this and making the program, which will presumably finish at some point not just be stuck in an infinite loop that happens to let the gui update lol
