### ISSUE TITLE
Image Cropping

### ISSUE THREAD

**Issue by poulsen93** [ciromattia/kcc#167]
Would it be possible to add a option to disable image cropping? Some it removes the entire margin of a page.

**Comment by AcidWeb** [comment]
It should remove entire margin. Unless it remove the actual content the image.

**Comment by AcidWeb** [comment]
Closed due lack of feedback.

**Comment by 3154** [comment]
I'm having the same issue, here is an example of it cropping content: http://imgur.com/a/p1frV

I want to use kcc because it uses the surface of my kindle (paperwhite 1, 2012) to its fullest, without leaving space at top and bottom. But I can't because it insists on cropping the input images. I'm sure there are things to crop, but since it can't do it without damages I'd be happy to turn it off and live with the gains in margin only.

**Comment by AcidWeb** [comment]
Working as indented. This is not a magic wand and it will fail in some cases. In most cases problems are caused by LQ input.

I can only suggest using CLI version to decrease cropping power.

**Comment by 3154** [comment]
I know. The issue is about adding it as a checkbox in the GUI. I was hoping to get it reopened by providing feedback.
