### ISSUE TITLE
Uploading through Calibre damage KEPUBs

### ISSUE THREAD

**Issue by leedashone** [ciromattia/kcc#184]
Dears,

I have two ebook reader, Kobo Glo & Aura H2O.
I convert few jpg to epub format, upload to reader with calibre
(no more convert in calibre), Every page is only show half of image.
(The bottom half of image show on top half of display)

Kobo Glo & H2O have same result. 

I Tryed every options (Upscale/PNG/Color......) , no change.
(I think maybe kobo can't handle html viewport correct....)

The test files and screenshot & device photo here:

https://www.dropbox.com/s/0w0lfy3tf9qjk7j/KCC%20issue.zip?dl=0

**Comment by AcidWeb** [comment]
Try this file on your H20: https://kcc.iosphe.re/Samples/Ubunchu-KoAH2O.kepub.epub

Upload manually - not using Calibre.

**Comment by leedashone** [comment]
It's work!!  
Upload epub manually is the answer of everything!
My test file and your test file have same result:
  - upload via calibre (even without convert) = error
  - Upload  manually = ok!
Thanks a lot!

**Comment by AcidWeb** [comment]
Good. Now only question - Why Calibre doing that? I will need to investigate this matter.

**Comment by AcidWeb** [comment]
Could you send me your test file directly from Kobo after Calibre upload?

**Comment by leedashone** [comment]
Download link:  https://www.dropbox.com/s/gtxyzfq6nfbql7k/KCC_Issue_184.zip?dl=0
There are 3 files in zip file:
1. Test Folder.kepub.epub  --> epub file made by KCC, contain 3 pages of jpeg file.
2. Writer, Test.zip  --> Use Calibre "add book",, then copy it from the Calibre Library folder.
3. Test Writer.zip --> Use Calibre upload epub to Kobo, Disconnect device, Close Calibre, 
     connect device again, then download it  from KOBOeReader USB device.

**Comment by davidfor** [comment]
AcidWeb asked for my comments, so...

Based on what I can see, the solution is to remove the ",epub" from the filename before adding the book to calibre.

The problem is that when you add this book to calibre, the extension says it is an epub. Then, when you send it to the Kobo device, it is sent as an epub and the RMSDK based epub renderer is used.

When you manually copy it to the device with the double extension of ".kepub.epub", this will have it treated as a kepub and use the kepub renderer. And the kepub renderer is needed for epub3 books. If the book is added to calibre as a kepub, then calibre will treat it as such and the KoboTouch driver will send it to the device as a kepub.

I would recommend installing the KePub Metadata Reader and KePub Metadata Writer plugins. These will allow calibre to get and update the metadata in kepubs. Calibre has some very basic handling of kepubs, but these plugins add the needed support. There are also conversion input and output plugins if you need them,

You can also use the KoboTouchExtended driver. With this, when an epub is sent to a Kobo device, it is automatically converted to a kepub. This makes a lot of changes to the epub that the kepub renderer expects. Without them, there will be problems such as remembering the current reading poition. But, for the code in the KCC generated kepubs, this isn't necessary.

**Comment by AcidWeb** [comment]
Thank you very much.

One additional question: Manually uploaded file with extension .kepub is detected correctly by Kobo? Or .kepub.epub is mandatory?

**Comment by leedashone** [comment]
I tryed rename the "Test Folder.kepub.epub"  to "Test Folder.kepub" then
Manually upload to Kobo, but nothing happen.
(That book don't show in Kobo's library)

**Comment by leedashone** [comment]
Ok, It's the next test,, same epub file (created via KCC), all manually upload, just rename:
Name: Test Folder.kepub.epub ==> Perfect!
Name: Test Folder.epub ==> Can show on Kobo, but layout mistake (only half page)
Name: Test Folder.kepub ==>  Kobo don't know what's this.

**Comment by AcidWeb** [comment]
OK. So can't do anything about it on KCC side. I will just update documentation.

**Comment by davidfor** [comment]
The rules are simple:
- If you manually sideload to the Kobo device, what happens depends on the extension. A file with ".epub" is treated as an epub and opened with the RMSDK renderer. A file with ".kepub.epub" will be treated as a a kepub.
- If you add the book to calibre, a file with ".kepub.epub" will be added as an epub (calibre only looks at the extension) but a file with just ".kepub" will be added as a kepub.
- When sending books from calibre to the Kobo device, an epub will sent as an epub and a kepub will be sent as a kepub. When the latter is done, the name is changed to end with ".kepub.epub".
- If you put a file with the extension ".kepub" on the Kobo device, it will be ignored as this is not an extension it expects.
