### ISSUE TITLE
Only the first image is included in the .mobi file

### ISSUE THREAD

**Issue by gonik** [ciromattia/kcc#204]
Hello there, thank you for the great piece of software. I own a Kindle Paperwhite 3 and I would like to convert my comic books in .mobi format.

While using your software to convert my cbr files, **only the first page of each comic (the cover) is showing up in the mobi file**, when viewing the output file in SumatraPDF.

I am selecting my Kindle from the Devices list and the MOBI/AZW3 from the output format list. From the checboxes below, only the Stretch/Upscale is selected. Am I doing something wrong?

**Comment by AcidWeb** [comment]
And what is displayed on real hardware?

**Comment by gonik** [comment]
To be honest I haven't checked how it appears in the Kindle, because everything I put it in I open it first in Sumatra to check if they are OK.
But you are right, I should test it on the device as well. I'll get back to you soon!

**Comment by AcidWeb** [comment]
I highly doubt that SumatraPDF can display  KCC output properly. Even Calibre can't.

MOBI creater by KCC are quite special and most of software can't render it properly.

**Comment by Verser** [comment]
I am getting this issue as well. I have some more data to add to this.

It creates the epub then the mobi file with no errors. If opened on the computer, the mobi opens in the kindle for windows app without problem, I can even scroll through the images and read it just fine.

Once it is loaded on the kindle, I can only swap between page one and two (or perhaps a zoomed in page one). You can use the go-to location and select a page farther down the book. Once you do, you have about three pages of scroll before it resets to the page 1->2->1 loop.

I have a kindle white version 3. And I've tried with an older gen that a co-worker had, getting to the same issue. So I am not sure where the problem lies, but it is a weird one. 

I've also recreated the file several times. And if it helps, it was generated from a series of .jpeg files and the finished mobi was a full 95mb. 

As for Sumatra, it is only able to read the first two pages as well.

**Comment by AcidWeb** [comment]
This is different issue. In left-to-right content next/prev page touch zones are swapped.

**Comment by gonik** [comment]
Hey AcidWeb,

I finally found some time today to test this on my Kindle. Indeed you are right, it displays OK in my Kindle. Sorry for not testing before opening this issue thread.

Thank you again for this great piece of software! I highly appreciate it :+1:
