### ISSUE TITLE
Renaming problem

### ISSUE THREAD

**Issue by cyberbad** [ciromattia/kcc#362]
can you add an option for not renaming files it's make some inversion depending the initial name

**Comment by darodi** [comment]
could you give an example?
What is the input?
What is expected?
What is the current result?

**Comment by 4AM-Campfire** [comment]
I've just run into this problem. My .cbz file was in the incorrect order after converting due to all the files being renamed during the process.

The problem part of the file name structure was:
Input:
"...c041 (v05) - p016..."
"...c041#1 (v05) - p017..."

Output:
"...c0041-v0005-p016..."
"...c0041-0001-v05-p017..."

Only some of the files have a "#1" or "#2" in them, and the renaming method makes them sort above where they were originally, so page 17 came before page 16.


My expected result would be that the converter wouldn't change the file names at all. I can understand adding the "-kcc" at the end, but that's it. The changing to lower case, removal of characters, the removal of spaces, and whatever its doing adding extra "0"s is unwanted.
