### ISSUE TITLE
Large files cannot be converted

### ISSUE THREAD

**Issue by augustebaum** [ciromattia/kcc#396]
I found a cbr which is 500 MB ([here](http://booksdl.org/comics0/_NON_ENG_ORIG/%21Incoming/%21%21Tri/%21Dixit/Manga%20FR/G/Grappler%20the%20baki/) if you're interested) and I'm trying to convert it to mobi with KCC. Though the software works great in general, I always get an error when I try to convert this one:
```
Error during conversion! Please consult wiki for more details.
```
I've managed to extract it with online tools (though not to convert it to mobi because all these websites have size limits of 300 MB or lower) so I don't think there is anything wrong with the file.
I haven't seen anything about this in the docs about size limits so I assume this is unwanted behaviour.

**Comment by origaniels** [comment]
Hi, 
I ran on a similar problem (got the same Error) when converting a 510 MB pdf file, but the issue wasn't of the size, but of the format of images. 
My file contained JPG and PNG images and KCC doesn't support PNGs. When converting each png to jpg it worked fine. 
Though KCC did split it in 2 separate files (parts 1/2 and 2/2), probably because of the size.
In any case there shouldn't be a problem with the size.

I don't know if that can solve your problem but you might want to try converting your PNG files to JPG (though with 500 MB you might need a program to do it for you...)

**Comment by darodi** [comment]
The cbr is just a zip file.
Unzip it and split the content in 2 smaller directories.
Then convert those 2 directories in KCC.
