### ISSUE TITLE
Windows cannot convert cbr in version 5.6.1

### ISSUE THREAD

**Issue by kurkasr** [ciromattia/kcc#489]
I can't convert cbr, cbz on Windows 11. KCC version 5.6.1
![image](https://user-images.githubusercontent.com/120309744/222946484-ba7b8493-7564-4889-b823-11bb3942545e.png)

**Comment by axu2** [comment]
Are you able to run KCC from source to get a more detailed error message?

**Comment by cookie99999** [comment]
I have encountered the same issue, both on Windows using the 5.6.1 release, and on Debian using the up to date repo. The issue seems to happen because p7zip on some/all platforms requires a separate plugin to work with rar files (p7zip-rar on Debian). The command will put corrupted image files into the working directory, which then causes unrar to fail, as its default behavior is to not overwrite files with the same name when extracting.

**Comment by darodi** [comment]
@kurkasr 

Could you give more information on the issue?
Is 7zip installed and in your system path?

**Comment by darodi** [comment]
should be fixed with
- #553

reopen another issue if needed
