### ISSUE TITLE
Add option to disable the new 3% cropping rule.

### ISSUE THREAD

**Issue by 4AM-Campfire** [ciromattia/kcc#585]
This feature has made my book almost unreadable as it cuts off text near the edge of the page.

I've disable cropping, as it I never want it, but this new cropping still happens. I'm using the Mac version 5.6.3.

**Comment by axu2** [comment]
Can you upload an example image? What are the dimensions?

**Comment by 4AM-Campfire** [comment]
Page was 3450x2475 being convert for a Kindle Voyage (1072x1448).

Here is an example, just three lines of text on the edge of the page:

![test](https://github.com/ciromattia/kcc/assets/26367788/c06416e4-e0db-4faa-a113-0d6fb5c3059b)

![kcc-0000-kcc-a](https://github.com/ciromattia/kcc/assets/26367788/b28e22cf-b54a-414c-93c4-40b97d191a8f)

**Comment by axu2** [comment]
I see, thanks for the information.

Problem is due to me testing on a Kindle with a wider aspect ratio than yours, so the provided image wouldn't be cropped. I've also never seen sideways text on a double page spread either.

For now, here's a build with the crop disabled: 

Mac:
https://github.com/axu2/kcc/actions/runs/6067486654

Windows:
https://github.com/axu2/kcc/actions/runs/6067497219

**Comment by 4AM-Campfire** [comment]
Thanks for the quick fix!

Tailoring the %crop to the device profile would probably be a good idea. I'm not sure what numbers would be acceptable for a given screen; I'll always fall on the side of never wanting to crop anything so can't make a fair suggestion.

**Comment by axu2** [comment]
I decided to dramatically lower the default auto crop threshold. In the future I'll make a 3-way toggle with 0/0.015/0.045(original) thresholds
