### ISSUE TITLE
double spread pages are split up in the "images" folder

### ISSUE THREAD

**Issue by Zephdoro** [ciromattia/kcc#593]
hey guys, this is my first time here. 
i got the kindle paperwhite 11th generation, i'm currently reading Berserk on it. so reading via amazon directly isn't the best experience since the quality is bad, the only good thing about it, is the feature to enable "Preview Double Page Spread" which shows a small preview of the double page on the bottom of the screen, so if u click it it will switch to landscape mode and lets u view the full page. So i did the thing to get all berserk mangas from amazon kindle unlimited onto my PC with an old kindle app. those files are now in AZW3. i then put those files into calibre to deDRM them. 

so what i did first was to just put the azw3 files into calibre and directly send it to my kindle. the quality did improve but whenever a double page appears, i need to manually switch to landscape mode, which is a little annoying.

i thought maybe KCC can change that, i converted the AZW3 file into ZIP in calibre and extracted it to get the "images" folder.
i put the "images" folder into kcc with these settings > (Manga Mode ✔️ Spread Splitter ✔️ Stretch/Upscale ✔️ Custom Gamma 1.00 ✔️ Cropping Mode 1.00 ✔️) after that i put the images folder onto calibre and directly sent it to my kindle, the quality got a little hit it wasn't as sharp as the AZW3 raw file. even tho i had spread splitter enabled, the double pages were still split up, i then looked into the "images" folder and noticed that all the double pages were 2 single pages and not one. 

is there a way to fix the double page problem and the quality deterioration? also the option to enable "Preview Double Page Spread" is that an amazon only thing or is there a way to add it as a feature on KCC?

i also tried converting the AZW3 to different formats such as MOBI,EPUB,KFX and PDF but the raw AZW3 files just looked a little better.

that was alot, hope u guys understood and can help :)

**Comment by Zephdoro** [comment]
* i used the kindle app version 1.7.1 for pc

**Comment by axu2** [comment]
This isn't a KCC issue. If your source has the double page spreads already split, there's no way for KCC to know to join them back together. We know this because the AZW3 you copied from the Kindle PC app to your Kindle doesn't show double page spreads either. When viewed on PC, you always view 2 pages at a time, so spread joining isn't needed, it always shows 2 pages at a time.

If you want double page spreads, you'll need a source file where the spreads are already joined, like: 

![image](https://github.com/ciromattia/kcc/assets/20757319/b430293c-d9ae-44b2-b57a-4e5634cd6834)

And use the rotate feature of KCC.
