### ISSUE TITLE
Disable file renaming for files with the same extension when input and output folders are different 

### ISSUE THREAD

**Issue by Leska1337** [ciromattia/kcc#652]
When input and output files have the same extension (CBZ to CBZ conversion for example) kcc automatically adds "kcc_" to the output file name. I understand why it's for, but this also happens when you choose different output folder via shift click.

**Comment by axu2** [comment]
I didn't know you could specify output folder. Where do I shift click? @Leska1337

**Comment by Leska1337** [comment]
Convert button. I move files to folder that I set up in Calibre and they are automatically added to my library. But like I said you have to rename them again by hand if the file extensions are the same. For now I rename my cbz input files to zip but this adds an extra step, so would be cool if this is changed in the next update.

**Comment by VampiroMedicado** [comment]
The problem seems to be because `options.output` isn't set. So, when the program tries not to overwrite files, it ends up using the only path it knows.

if `wantedname` is given, it looks for a name in that directory using `options.output`:

https://github.com/ciromattia/kcc/blob/e8502f008a658211370aad001c0511150afdbdc4/kindlecomicconverter/comic2ebook.py#L666-L673

With this change https://github.com/ciromattia/kcc/commit/69b4ee5ea89fe20a06cbddea6f714eaf092abb87 the issue seems to be fixed.

@Leska1337 can you check if it works correctly for you? #657

https://github.com/ciromattia/kcc/wiki/Installation#install-from-source

**Comment by Leska1337** [comment]
Yeah, it does, ty
